#!/bin/bash

courses=("Computer Science" "Engineering" "Mathematics" "Biology" "History")
count=${#courses[@]}

# Create a file to store the matric and password
output_file="matric_password.txt"
> "$output_file" # Clear the file

for i in {1..20}
do
  matric="AB$(shuf -i 10000-99999 -n 1)"
  password="Pass$(shuf -i 1000-9999 -n 1)"
  email="user$i@example.com"
  random_index=$(shuf -i 0-$(($count - 1)) -n 1)
  courseOfStudy="${courses[$random_index]}"
  admissionType="BSc"

  # Append matric and password to the file
  echo "Matric: $matric, Password: $password" >> "$output_file"

  # Send a POST request to your endpoint
  curl -X POST -d "matric=$matric&password=$password&email=$email&courseOfStudy=$courseOfStudy&admissionType=$admissionType" http://localhost:1245/signup
done
